### ISSUE TITLE
Proszę o pomoc w uruchomieniu 

### ISSUE THREAD

**Issue by kmarek1** [wasilukm/hoymiles-mqtt#8]
* Hoymiles MQTT version: [0.2.0 → 0.3.0]
* Python version:3.10
* Operating System:

mam taki log przy uruchomieniu 
Using username "user1".
user1@192.168.10.121's password:
Linux homeAssistant 6.0.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.5-1 (2022-10-28) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Oct 31 15:44:45 2022 from 192.168.10.113
user1@homeAssistant:~$ python -m pip install hoymiles-mqtt
-bash: python: command not found
user1@homeAssistant:~$ python3 -m pip install hoymiles-mqtt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: hoymiles-mqtt in /usr/local/lib/python3.10/dist-packages (0.3.0)
Requirement already satisfied: mkdocs-material-extensions<2.0.0,>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from hoymiles-mqtt) (1.1)
Requirement already satisfied: paho-mqtt<2.0.0,>=1.6.1 in /usr/local/lib/python3.10/dist-packages (from hoymiles-mqtt) (1.6.1)
Requirement already satisfied: ConfigArgParse<2.0.0,>=1.5.3 in /usr/local/lib/python3.10/dist-packages (from hoymiles-mqtt) (1.5.3)
Requirement already satisfied: hoymiles-modbus==0.5.0 in /usr/local/lib/python3.10/dist-packages (from hoymiles-mqtt) (0.5.0)
Requirement already satisfied: plum-py==0.8.0 in /usr/local/lib/python3.10/dist-packages (from hoymiles-modbus==0.5.0->hoymiles-mqtt) (0.8.0)
Requirement already satisfied: pymodbus<3.0.0,>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from hoymiles-modbus==0.5.0->hoymiles-mqtt) (2.5.3)
Requirement already satisfied: pyserial>=3.4 in /usr/local/lib/python3.10/dist-packages (from pymodbus<3.0.0,>=2.5.3->hoymiles-modbus==0.5.0->hoymiles-mqtt) (3.5)
Requirement already satisfied: six>=1.15.0 in /usr/lib/python3/dist-packages (from pymodbus<3.0.0,>=2.5.3->hoymiles-modbus==0.5.0->hoymiles-mqtt) (1.16.0)
user1@homeAssistant:~$ python3 -m hoymiles_mqtt --mqtt-broker 192.168.10.121 --dtu-host 192.168.10.204
Exception in thread Thread-1 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
Exception in thread Thread-2 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
Exception in thread Thread-3 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
Exception in thread Thread-4 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
Exception in thread Thread-5 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
Exception in thread Thread-6 (execute):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/runners.py", line 43, in execute
    self._mqtt_publisher.publish(topic=topic, message=payload, retain=True)
  File "/usr/local/lib/python3.10/dist-packages/hoymiles_mqtt/mqtt.py", line 33, in publish
    publish_single(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 240, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 177, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/publish.py", line 55, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.

zainstalowany mam  Mosquitto broker bez haseł 
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[15:55:11] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:55:12] INFO: Starting NGINX for authentication handling...
[15:55:13] INFO: Starting mosquitto MQTT broker...
2022-10-31 15:55:13: Warning: Mosquitto should not be run as root/administrator.
[15:55:18] INFO: Successfully send discovery information to Home Assistant.
[15:55:21] INFO: Successfully send service information to the Supervisor.
2022-10-31 15:55:13: mosquitto version 2.0.11 starting
2022-10-31 15:55:13: Config loaded from /etc/mosquitto/mosquitto.conf.
2022-10-31 15:55:13: Loading plugin: /usr/share/mosquitto/go-auth.so
2022-10-31 15:55:13:  ├── Username/password checking enabled.
2022-10-31 15:55:13:  ├── TLS-PSK checking enabled.
2022-10-31 15:55:13:  └── Extended authentication not enabled.
2022-10-31 15:55:13: Opening ipv4 listen socket on port 1883.
2022-10-31 15:55:13: Opening ipv6 listen socket on port 1883.
2022-10-31 15:55:13: Opening websockets listen socket on port 1884.
2022-10-31 15:55:13: mosquitto version 2.0.11 running
2022-10-31 15:55:14: New connection from 127.0.0.1:42260 on port 1883.
2022-10-31 15:55:14: Client <unknown> closed its connection.
2022-10-31 15:58:28: New connection from 172.30.32.1:58500 on port 1883.
2022-10-31 15:58:28: New client connected from 172.30.32.1:58500 as mqtt_hoymiles_dtu_52c033f3-26f2-4f8a-bd6c-297a2bd9fb1a (p2, c1, k60, u'addons').
2022-10-31 16:01:27: New connection from 192.168.10.121:60211 on port 1883.
error: received null username or password for unpwd check
2022-10-31 16:01:27: Client <unknown> disconnected, not authorised.
2022-10-31 16:02:24: New connection from 192.168.10.121:56673 on port 1883.
error: received null username or password for unpwd check
2022-10-31 16:02:24: Client <unknown> disconnected, not authorised.
2022-10-31 16:03:24: New connection from 192.168.10.121:57065 on port 1883.
error: received null username or password for unpwd check
2022-10-31 16:03:24: Client <unknown> disconnected, not authorised.
2022-10-31 16:04:24: New connection from 192.168.10.121:58687 on port 1883.
error: received null username or password for unpwd check
2022-10-31 16:04:24: Client <unknown> disconnected, not authorised.
2022-10-31 16:05:24: New connection from 192.168.10.121:56847 on port 1883.
error: received null username or password for unpwd check
2022-10-31 16:05:24: Client <unknown> disconnected, not authorised.
2022-10-31 16:06:24: New connection from 192.168.10.121:60487 on port 1883.
error: received null username or password for unpwd check

**Comment by wasilukm** [comment]
Wygląda na problem z konfiguacją MQTT brokera: https://forum.arturhome.pl/t/mqtt-error-received-null-username-or-password-for-unpwd-check/5935/2
